apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-service
  namespace: product-catalogue
spec:
  type: NodePort
  selector:
    app: product-catalogue
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080